name: Code Quality Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check for file encoding issues
        run: |
          echo "Checking for non-UTF-8 encoded files..."
          find . -type f -name "*.py" -exec file --mime {} \; | grep -v "charset=utf-8" || true

      - name: Check for null bytes
        run: |
          echo "Checking for null bytes in Python files..."
          find . -type f -name "*.py" -exec grep -l -P "\x00" {} \; || true

      - name: Check for merge conflicts
        run: |
          echo "Checking for merge conflict markers..."
          find . -type f -name "*.py" -exec grep -l "<<<<<<< HEAD" {} \; || true
          find . -type f -name "*.py" -exec grep -l "=======" {} \; || true
          find . -type f -name "*.py" -exec grep -l ">>>>>>> " {} \; || true

      - name: Check for code issues
        run: |
          python fix_code_issues.py --check-only

      - name: Check for syntax errors
        run: |
          python -m compileall .
