name: Python Tests

on:
  push:
    branches: [ main, conditional-actions ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install test dependencies
        pip install pytest pytest-cov
        
    - name: List directory structure
      run: |
        find . -type f -name "*.py" | sort
        
    - name: Run tests
      run: |
        # Add the src directory to PYTHONPATH
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        # Run tests with coverage
        python -m pytest tests/ -v --cov=src
